# Generated by Django 3.0.6 on 2020-05-06 03:47
#これはmakemigrationsをしたときにできました
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),#あ！俺が作ったやつや！
                ('memo', models.TextField()),
            ],
        ),
    ]
